### ISSUE TITLE
limit as parameter in getPosts()

### ISSUE THREAD

**Issue by tempe-techie** [OrbisWeb3/orbis-sdk#7]
Currently the [getPosts()](https://github.com/OrbisWeb3/orbis-sdk/blob/7602dce9aa7d84c388590771fd94edfb1893ebcf/index.js#L1345) function in the SDK has a hardcoded post limit at `50`.

It would be great if limit was a parameter so that developers could choose a different size limit:

```js
async getPosts(options, page = 0, limit = 50) {
```

If that only requires changes in this function (and no backend changes), I can do that and push it as PR, to save you some time. Please let me know @baptistegreve 🙂

**Comment by orbis-gh** [comment]
I actually worked on this last week and it should be available now in version `0.4.32` of the SDK! I will add this to the doc but for now here it is: https://github.com/OrbisWeb3/orbis-sdk/blob/master/index.js#L1324

**Comment by tempe-techie** [comment]
Awesome, thanks @baptistegreve 🤩 Will update to the newest SDK version 🙂
